# Metode Pengambilan Sampel

Pengumpulan data SKD 2024 dilaksanakan di Unit Pelayanan Statistik Terpadu (PST) pada satker BPS Pusat, BPS Provinsi, dan BPS Kabupaten/Kota seluruh Indonesia. Periode pengumpulan data adalah pada 1 Maret - 31 Desember 2024, sedangkan referensi waktu dari data yang dikumpulkan adalah 1 Januari 2024 sampai dengan saat pencacahan.

## Metode Pengumpulan Data

SKD 2024 dilaksanakan dengan metode *nonprobability sampling*, yaitu teknik yang tidak memberi peluang/kesempatan bagi setiap unsur atau anggota populasi untuk dipilih menjadi sampel. Unit sampel SKD 2024 adalah konsumen yang menerima layanan di unit PST BPS. Teknik pengambilan sampel yang digunakan adalah quota sampling, yaitu suatu pengambilan sampel dari populasi yang mempunyai ciri-ciri tertentu sampai jumlah/kuota yang diinginkan atau jumlah subjek yang diselidiki tercapai sesuai yang telah ditetapkan. Agar target sampel dapat terpenuhi, mekanisme pengambilan sampel dilakukan dengan cara memilih sampel dari daftar konsumen yang menerima layanan mulai 1 Januari 2024 sampai dengan akhir periode pengumpulan data (31 Desember 2024). Daftar konsumen dapat diperoleh dari beberapa sumber, seperti:

1.  Buku tamu PST (baik manual maupun *online* melalui pst.bps.go.id). Pada wilayah yang menyediakan layanan kunjungan langsung, baik melalui PST dan unit kerja lain *(subject matter*), semua konsumen tersebut dicakup dalam daftar konsumen;

2.  Pengguna website yang mengunduh publikasi;

3.  Pengguna aplikasi Chat Us; dan

4.  Pengguna aplikasi layanan statistik lainnya yang ada di masing-masing satker BPS.

Selain itu, sampel juga dapat berasal dari konsumen yang menerima layanan secara *online* dan berpartisipasi secara mandiri dalam SKD 2024 dengan mengakses link kuesioner yang tersedia pada layanan *online*.

## Metode Analisis Data

Metode pengumpulan data pada sakter BPS Kabupaten Sikka dilakukan dengan dua cara, yaitu wawancara langsung kepada responden dan pendataan mandiri (*self-enumeration*) atau swacacah oleh responden. Pengumpulan data dengan metode wawancara langsung disarankan dilakukan pada pertanyaan Blok I dan Blok III Kolom 1-10 VKD24. Namun, jika tidak memungkinkan untuk wawancara (misal karena tidak bisa ditemui secara tatap muka atau telepon), maka pengumpulan data dapat dilakukan melalui pendataan mandiri/swacacah dengan cara responden diminta untuk mengisi kuesioner sendiri. Pendataan mandiri juga dilakukan untuk pertanyaan persepsi kepentingan dan kepuasan responden terhadap pelayanan dan data BPS yang ada pada Blok II dan Blok III Kolom 11 VKD24. Moda pengumpulan data SKD 2024 melalui:

1.  *Computer Assisted Web Interviewing* (CAWI), yaitu pengumpulan data dengan menggunakan aplikasi berbasis website. Dalam SKD 2024, penggunaan moda ini dibedakan menjadi 3 (tiga), yaitu *online*-PST, *online*-email, dan *online*-link yang akan dijelaskan pada Subbab 3.2.

2.  *Pencil-and-Paper Interviewing* (PAPI), yaitu pengumpulan data dengan menggunakan kuesioner dalam bentuk media kertas (*hardcopy*). Penggunaan moda PAPI diutamakan untuk wilayah yang terkendala sinyal, jaringan, atau operasional teknologi di lapangan. Moda PAPI juga dapat digunakan untuk konsumen yang datang langsung ke PST dan tidak bisa mengakses secara *online*.

Metode analisis yang digunakan adalah analisis deskriptif yang disajikan dalam bentuk tabel, grafik, dan infografis. Beberapa bentuk analisis deskriptif yang digunakan adalah analisis tabulasi silang, analisis kesenjangan (*gap analysis*), *Importance and Performance Analysis* (IPA), Indeks Kepuasan Konsumen (IKK), Indeks Kepuasan Masyarakat (IKM), Indeks Persepsi Kualitas Pelayanan (IPKP), dan Indeks Persepsi Anti Korupsi (IPAK).

a.  Analisis Tabulasi Silang

Analisis tabulasi silang adalah analisis yang menggunakan tabel untuk menggambarkan hubungan antara dua atau lebih variabel. Perbedaan dan persamaan antara dua atau lebih variabel dapat diidentifikasi dengan tabulasi silang.

b.  Analisis Kesenjangan

Analisis kesenjangan atau gap analysis adalah analisis yang digunakan untuk mengetahui kesenjangan antara harapan (tingkat kepentingan) terhadap kinerja (tingkat kepuasan) dari pelayanan yang diberikan oleh unit pelayanan yang bersangkutan. Pada analisis kesenjangan, harapan konsumen akan dibandingkan dengan kinerja pelayanan yang diberikan (*delivered*) oleh unit pelayanan. Nilai kesenjangan atau gap diperoleh dari selisih antara tingkat kepuasan dan tingkat kepentingan pengguna layanan pada setiap rincian pelayanan. Nilai kesenjangan dapat bernilai positif atau negatif. Gap positif diperoleh apabila tingkat kepuasan lebih besar dari tingkat kepentingan. Jika nilai gap positif semakin besar, maka konsumen semakin puas. Nilai gap negatif diperoleh apabila tingkat kepuasan lebih kecil dibanding tingkat kepentingan. Jika nilai gap negatif semakin kecil, maka konsumen semakin tidak puas.

c.  *Importance and Performance Analysis* (IPA)

Metode IPA dikenal pula dengan istilah analisis kuadran (quadrant analysis). Metode ini pertama kali diperkenalkan oleh Martilla dan James (1977). Tujuan metode ini adalah mengukur hubungan antara persepsi konsumen dengan prioritas peningkatan kualitas produk/jasa (Brandt, 2000 dan Latu, 2000). IPA mempunyai fungsi utama untuk menampilkan informasi tentang faktor-faktor pelayanan yang sangat memengaruhi kepuasan dan peningkatan pelayanan (improvement). IPA telah diterima secara umum dan digunakan pada berbagai

bidang kajian karena kemudahan untuk diterapkan dan tampilan hasil analisis yang memudahkan usulan perbaikan kinerja (Martinez, 2003). Dalam IPA terdapat dua pendekatan yang digunakan, yaitu:

1.  Tingkat Kesesuaian

Penghitungan tingkat kesesuaian digunakan untuk mengetahui seberapa besar konsumen merasa puas terhadap kinerja pelayanan. Tingkat kesesuaian adalah hasil perbandingan tingkat kepuasan dan tingkat kepentingan. Tingkat kesesuaian dihitung menggunakan rumus berikut:

$$
TK = \frac{\bar x}{\bar y} \times 100\%
$$

dengan: $TK$ adalah tingkat kesesuaian, $\bar x$ = rata-rata tingkat kepuasan, dan $\bar y$ = rata-rata tingkat kepentingan.

Kriteria penilaian tingkat kesesuaian adalah:

-    $TK > 100\%$ berarti kinerja pelayanan melebihi harapan konsumen,

-   $TK = 100\%$ berarti kinerja pelayanan sesuai harapan konsumen,

-   $TK < 100\%$ berarti kinerja pelayanan belum sesuai harapan konsumen.

2.  Diagram cartesius

Diagram cartesius merupakan analisis yang digunakan untuk menggambarkan hubungan antara tingkat kepentingan (importance) dan tingkat kepuasan (performance). Pada Gambar 1.1, diagram cartesius dibagi atas empat bagian yang dibatasi oleh dua buah garis yang berpotongan tegak lurus pada titik $(\bar x, \bar y)$ dengan $\bar x$ adalah rata-rata tingkat kepuasan dan $\bar y$ adalah rata-rata tingkat kepentingan.

\[Gambar 1.1 Diagram Cartesius Importance and Performance Analysis\]

Masing-masing kuadran yang terbentuk memiliki makna yang berbeda.

-   Kuadran A (*high importance and low performance*);

    Kuadran A terletak di sebelah kiri atas atau kuadran “Tingkatkan Kinerja” yang berarti bahwa prioritas utama dari suatu atribut pelayanan adalah peningkatan kinerja (performance improvement). Kuadran ini memuat atribut pelayanan yang dianggap penting oleh pengguna layanan, tetapi faktanya kinerja atribut pelayanan tersebut belum sesuai dengan harapan para pengguna layanan. Dengan kata lain, kinerja atribut pelayanan tersebut lebih rendah dari harapan pengguna layanan terhadap atribut pelayanan tersebut. Atribut pelayanan yang terdapat dalam kuadran ini harus lebih ditingkatkan agar dapat memenuhi harapan pemangku kepentingan/pengguna layanan. Cara yang dapat dilakukan oleh penyedia layanan adalah perbaikan secara terus menerus terhadap kinerja, sehingga performance dari atribut pelayanan yang ada dalam kuadran ini akan meningkat.

-   Kuadran B (*high importance and high performance*);

    Kuadran B atau Kuadran “Pertahankan Kinerja” terletak di sebelah kanan atas, yang memiliki arti bahwa kinerja suatu atribut pelayanan sudah dapat memenuhi harapan pengguna layanan dan penyedia layanan harus berusah mempertahankan kinerja tersebut. Kuadran ini memuat atribut pelayanan yang dianggap penting oleh pengguna layanan dan kinerja atribut pelayanan dianggap sudah sesuai dengan yang dirasakan oleh pengguna layanan, sehingga tingkat kepuasannya relatif tinggi. Kinerja atribut pelayanan yang termasuk dalam kuadran ini harus dipertahankan.

-   Kuadran C (*low importance and low performance*);

    Kuadran C terletak di sebelah kiri bawah atau disebut sebagai Kuadran “Prioritas Rendah”. Kuadran ini memuat atribut pelayanan yang dianggap kurang penting oleh pengguna layanan dan faktanya kinerja atribut pelayanan tersebut tidak terlalu istimewa. Peningkatan kinerja atribut pelayanan yang termasuk dalam kuadran ini bukan menjadi prioritas utama, sehingga dapat dipertimbangkan kembali karena pengaruhnya terhadap manfaat yang dirasakan oleh pemangku kepentingan/pengguna layanan sangat kecil.

-   Kuadran D;

    Kuadran *“cenderung berlebihan”* terletak di sebelah kanan bawah mempunyai arti kinerja yang berlebihan namun pengguna layanan menganggap kurang penting. Kuadran ini memuat atribut pelayanan yang dianggap kurang penting oleh pemangku kepentingan/pengguna layanan. Kinerja atribut pelayanan dalam kuadran ini dapat dikurangi agar penyedia layanan dapat melakukan penghematan sumber daya.

## Cakupan Responden

Responden SKD 2024 adalah konsumen yang menerima pelayanan dari unit PST BPS Kabupaten Sikka sejak 1 Januari 2024 sampai dengan akhir periode pengumpulan data (31 Desember 2024). Pelayanan yang diberikan dari Unit PST BPS Kabupaten Sikka dapat melalui tatap muka yaitu konsumen datang langsung ke Unit PST BPS; tanpa tatap muka melalui media telepon, faksimile, dan surat; atau melalui media daring (*online*) seperti website BPS, aplikasi Allstats BPS, PST *online*, e-mail, atau media layanan lainnya. Ketentuan responden SKD 2024 dapat dilihat pada **Error! Reference source not found..**

## Target Responden

Target responden SKD 2024 secara nasional sebanyak 16.930 orang. Jumlah tersebut terbagi atas Unit PST BPS Pusat, BPS Provinsi, dan BPS Kabupaten/Kota (Tabel 1). Penghitungan jumlah sampel konsumen/responden minimum dilakukan dengan formula berikut:

$$
Z =  \frac{Z^2 p(1-p)}{e^2} \times \frac{1}{r}
$$

dengan:

$p$ = perkiraan proporsi kejadian terhadap target populasi (khusus kejadian yang belum diketahui diperkirakan sebesar 0,5),

$e$ = *margin of error* (toleransi kesalahan estimasi karena sampel yang diambil tidak dapat mewakili populasinya). MoE tingkat provinsi ditentukan 12,35% dan tingkat kabupaten/kota 19%.

$r$ = toleransi tingkat respons minimum

| No. | Wilayah PST        | Jumlah Unit PST | Target per Unit (Orang) | Target Responden (Orang) |
|:---:|:--------------------------------|------:|---------:|--------------:|
| 1\. | BPS Pusat          |               1 |                     150 |                      150 |
| 2\. | BPS Provinsi       |              35 |                      70 |                    2.450 |
| 3\. | BPS Kabupaten Kota |             491 |                      30 |                   14.730 |
|     |                    |                 |                  Jumlah |               **17.730** |

: Target Responden {#tbl-target-responden}

Kegiatan survei yang menggunakan metode non-probability sampling tidak mensyaratkan adanya ukuran sampel minimum karena disesuaikan dengan kebutuhan peneliti/pelaksana survei. Namun demikian, menurut beberapa penelitian, ukuran sampel yang dikatakan cukup untuk survei dengan metode sampling non-probability sampling adalah sebanyak 30 responden (Creswell, 2013, dan Saunders, 2016). Ukuran sampel yang dibutuhkan akan lebih besar seiring dengan semakin heterogen keadaan populasinya (Saunders, 2016, dan Guest, et al, 2006). Hal ini juga terkait dengan semakin luas wilayah cakupan responden.

## Variabel yang Dikumpulkan

Variabel yang dikumpulkan pada SKD 2024 meliputi:

-   **Keterangan Pencacahan**

-   **Blok I. Keterangan Responden**, meliputi nama, e-mail, nomor handphone, jenis kelamin, pendidikan tertinggi yang ditamatkan, pekerjaan utama, kategori instansi/institusi, nama instansi/institusi, pemanfaatan utama hasil kunjungan dan/atau akses layanan, jenis layanan yang digunakan, sarana yang digunakan untuk memperoleh layanan BPS, dan pengaduan terkait Pelayanan Statistik Terpadu (PST).

-   **Blok II. Kepuasan terhadap Pelayanan Data dan Informasi Statistik BPS**, mencakup 17 rincian kondisi pelayanan BPS, yaitu penilaian terhadap pelayanan BPS terkait kesesuaian antara standar pelayanan dan yang diberikan kepada konsumen; penilaian terkait aspek zona integritas; dan ukuran penilaian konsumen untuk pengukuran indikator SDGs terkait pelayanan publik di BPS.

-   **Blok III. Kebutuhan Data**, meliputi data yang dibutuhkan/ dikonsultasikan (jenis, tahun, level, dan periode data), perolehan data, sumber data (jenis, judul, dan tahun sumber data), penggunaan data yang diperoleh untuk perencanaan, monitoring, dan evaluasi pembangunan nasional/daerah, serta tingkat kepuasan konsumen terhadap kualitas data.

-   **Blok IV. Catatan**, berisi informasi tentang catatan, saran, atau kritik demi peningkatan kualitas layanan data, baik dari sisi petugas, ketersediaan data/informasi, maupun sarana dan prasarana layanan.

## Jadwal Kegiatan

Rangkaian pelaksanaan SKD 2024 dapat dilihat pada @tbl-jadwal-skd.

| Kegiatan                              | Waktu                         |
|---------------------------------------|-------------------------------|
| 1\. Identifikasi Kebutuhan Data       | M2 – M4 Jan                   |
|                                       |                               |
| 2\. Perancangan                       | M4 Jan – M2 Feb               |
|                                       |                               |
| 3\. Implementasi Rancangan            | M2 – M3 Februari              |
| 3.1. Briefing Petugas                 | M4 Februari                   |
|                                       |                               |
| 4\. Pengumpulan Data                  |                               |
| 4.1. Survei Kepuasan Masyarakat (SKM) | Maret – Desember              |
| 4.2. Survei Kebutuhan Data (SKD)      | Maret – Desember              |
|                                       |                               |
| 5\. Pengolahan Data                   |                               |
| 5.1. SKM Triwulanan                   | M4 Maret – M1 April           |
|                                       | M4 Juni – M1 Juli             |
|                                       | M4 September – M1 Oktober     |
|                                       | M4 Desember – M1 Januari 2025 |
| 5.2. SKM Semesteran                   | M4 Juni – M1 Juli             |
|                                       | M4 Desember – M1 Januari 2025 |
| 5.3. SKD Tahunan                      | Oktober - November            |
|                                       |                               |
| 6\. Analisis Data                     |                               |
| 6.1. SKM - Triwulanan                 | M1 April                      |
|                                       | M1 Juli                       |
|                                       | M1 Oktober                    |
|                                       | M1 Januari 2025               |
| 6.2. SKM - Semesteran                 | M1 Juli & M1 Januari 2025     |
| 6.3. SKD - Tahunan                    | M3 November – M1 Desember     |
|                                       |                               |
| 7\. Diseminasi Data                   |                               |
| 7.1. SKM - Triwulanan                 | M1 April                      |
|                                       | M1 Juli                       |
|                                       | M1 Oktober                    |
|                                       | M1 Januari 2025               |
| 7.2. SKM - Semesteran                 | M1 Juli & M1 Januari 2025     |
| 7.3. SKD - Tahunan                    | M1 Desember                   |
|                                       |                               |
| 8\. Evaluasi                          |                               |
| 8.1. SKM - Triwulanan                 | M2 April                      |
|                                       | M2 Juli                       |
|                                       | M2 Oktober                    |
|                                       | M2 Januari 2025               |
| 8.2. SKM - Semesteran                 | M2 Juli & M2 Januari 2025     |
| 8.3. SKM - Tahunan                    | M2 – M3 Januari 2025          |
| 8.4. SKD                              | M2 – M3 Desember              |

: Jadwal Kegiatan SKD 2024 {#tbl-jadwal-skd tbl-colwidths="\[60,40\]"}
