# Pengolahan Data

 ```{=tex}
\clearpage
\clearpage
```

Pengolahan data hasil SKD2024 pada triwulan II mencakup realisasi hasil pengumpulan data dan tingkat kepuasan pengguna terhadap layanan PST BPS Kabupaten Sikka.Hasil pengolahan data berupa jumlah, persentase, dan indeks yang disajikan dalam bentuk table dan grafik.

## Tabulasi Data

Pengolahan data menggunakan tabel silang untuk menggambarkan hubungan dua atau lebih variabel. Perbedaan dan persamaan antara dua atau lebih variable dapat diidentifikasi dengan tabulasi silang. Dalam analisis data, tabulasi silang akan memudahkan dalam memahami distribusi realisasi responden hasil pengumpulan data.

## Indeks Kepuasan Konsumen (IKM) Metode BPS

Indeks Kepuasan Konsumen (IKK) merupakan ukuran untuk menilai tingkat kepuasan konsumen terhadap pelayanan yang diberikan oleh unit PST BPS. Dengan demikian, IKK yang dihitung dalam SKD 2024 adalah IKK terhadap pelayanan PST BPS. IKK terhadap pelayanan PST BPS diperoleh dengan menghitung rata-rata tertimbang skor tingkat kepuasan berdasarkan 12 atribut pertanyaan (variabel) yang terdapat dalam Blok II kuesioner VKD24.

Langkah-langkah penghitungan IKK sebagai berikut:

1.  Menghitung Penimbang

Penimbang diperoleh dengan cara membagi rata-rata tingkat kepentingan masing-masing atribut pelayanan dengan jumlah rata-rata tingkat kepentingan seluruh atribut pelayanan. Rumus penimbang:

$$
w_i = \frac{\bar y_i}{\sum_{i = 1}^{12} {\bar y_i}}
$$

dengan: 

$w_i$ adalah penimbang atribut pelayanan ke-$i$, $\sum_{i=1}^{12}{w_i} = 1$

$y_i$ adalah rata-rata tingkat kepentingan atribut pelayanan ke-$i$, $i$ = 1, 2, …, 12

2.  Menghitung Rata-Rata Tertimbang Skor Kepuasan ($IKK’$)

$IKK’$ diperoleh dengan cara menghitung rata-rata tertimbang skor kepuasan berdasarkan 12 atribut pelayanan.

Rumus IKK’:

$$
IKK' = \frac{\sum_{i=1}^{12}{w_i \times \bar x_i}}{\sum_{i=1}^{12}{w_i}}
$$

dengan $x_i$ adalah rata-rata tingkat kepuasan atribut pelayanan ke-$i$

3.  Menghitung IKK

Penghitungan $IKK’$ menghasilkan nilai yang berkisar antara 1 sampai 10 sesuai dengan skala penilaian konsumen. $IKK$ merupakan hasil konversi nilai $IKK’$ menggunakan rumus berikut:

$$
IKK = \frac{IKK'}{\text{Skala maksimum penilaian}} \times 100 = \frac{IKK'}{10} \times 100
$$

Nilai IKK berdasarkan Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 14 Tahun 2017 tentang Pedoman Penyusunan Survei Kepuasan Masyarakat Unit Penyelenggara Pelayanan Publik dikategorikan menjadi 4 sebagaimana dalam @tbl-nilai-kinerja-1.

| Nilai[^04-pengolahan-data-1] | Kinerja Unit Pelayanan |
|:----------------------------:|:----------------------:|
|        25,00 - 64,99         |       Tidak Baik       |
|        65,00 - 76,60         |      Kurang Baik       |
|        76,61 - 88,30         |          Baik          |
|        88,31 - 100,0         |      Sangat Baik       |

: Nilai Kinerja Unit Pelayanan {#tbl-nilai-kinerja-1}

[^04-pengolahan-data-1]: Sumber: Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi, Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 14 Tahun 2017 tentang Pedoman Penyusunan Survei Kepuasan Masyarakat Unit Penyelenggara Pelayanan Publik

## Indeks Kepuasan Masyarakat (IKM) Metode KemenPANRB

Indeks Kepuasan Masyarakat (IKM) merupakan ukuran kualitas pelayanan yang diberikan oleh unit PST BPS sebagai unit penyelenggara pelayanan publik di BPS. Penghitungan IKM berpedoman pada Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 14 Tahun 2017 tentang Pedoman Penyusunan Survei Kepuasan Masyarakat Unit Penyelenggara Pelayanan Publik. IKM diperoleh dengan menghitung rata-rata tertimbang skor tingkat kepuasan berdasarkan 9 atribut pertanyaan (variabel) sebagaimana diatur dalam peraturan tersebut yang terdapat dalam Blok II kuesioner VKD24.

| Kode | SKM KemenPANRB              | Kode | SKD BPS                    |
|-------|---------------------|------|---------------------------------------|
| U1   | Kesesuaian Persyaratan      | R2   | Persyaratan pelayanan yang ditetapkan mudah dipenuhi/disiapkan oleh konsumen.|
| U2   | Prosedur Pelayanan          | R3   | Prosedur/alur pelayanan yang ditetapkan mudah diikuti/dilakukan.|
| U3   | Kecepatan Pelayanan         | R4   | Jangka waktu penyelesaian pelayanan yang diterima sesuai dengan yang ditetapkan.|
| U4   | Kesesuaian/ Kewajaran Biaya | R5   | Biaya pelayanan yang dibayarkan sesuai dengan biaya yang ditetapkan.  |
| U5   | Kesesuaian Pelayanan        | R6   | Produk pelayanan yang diterima sesuai dengan yang dijanjikan.  |
| U6   | Kompetensi Petugas          | R10  | Petugas pelayanan dan/atau aplikasi pelayanan *online* mampu memberikan informasi yang jelas.                |
| U7   | Perilaku Petugas Pelayanan  | R8   | Petugas pelayanan dan/atau aplikasi pelayanan online merespon dengan baik.  |
| U8   | Penanganan Pengaduan        | R12  | Proses penanganan pengaduan PST mudah diketahui, jelas, dan tidak berbelit-belit. (Ditanyakan jika responden pernah melakukan pengaduan)      |
| U9   | Kualitas Sarana dan Prasarana| R7   | Sarana dan prasarana pendukung pelayanan memberikan kenyamanan.|
|      |                             | R11  | Keberadaan fasilitas pengaduan PST mudah diketahui.|

: Kesesuaian Atribut Pelayanan antara Kementerian PANRB dan BPS {#tbl-kesesuaian-atribut}

Nilai IKM digunakan dalam pembangunan dan evaluasi Reformasi Birokrasi pada BPS dalam mendukung program Reformasi Birokrasi di Instansi Pemerintah sebagaimana diatur dalam Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 3 Tahun 2023 tentang Perubahan atas Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 25 Tahun 2020 tentang Road Map Reformasi Birokrasi 2020-2024.

Langkah-langkah penghitungan IKM sebagai berikut:

1.  Menghitung Penimbang

Penimbang diperoleh dengan menggunakan "nilai rata-rata tertimbang" masing-masing atribut pelayanan. Dalam penghitungan penimbang, setiap atribut pelayanan memiliki penimbang yang sama. Nilai penimbang ditetapkan dengan rumus, sebagai berikut:

$$
\text{Bobot nilai rata-rata tertimbang} = \frac{\text{Jumlah Bobot}}{\text{Jumlah Atribut}} = \frac {1}{X} = N
$$

dengan $N$ adalah bobot nilai per unsur. Sehingga nilai penimbang sebagai berikut.

$$
\text{Bobot nilai rata-rata tertimbang} = \frac{\text{Jumlah Bobot}}{\text{Jumlah Atribut}} = \frac {1}{9} = 0,11
$$

2.  Menghitung IKM

Penghitungan IKM menggunakan pendekatan nilai rata-rata tertimbang dengan rumus sebagai berikut:

$$
IKM' = \frac{\text{Total Nilai Persepsi per Atribut Pelayanan}}{\text{Total Atribut Pelayanan yang diisi}} \times \text{Nilai Penimbang}
$$

Untuk pelaporan IKM kepada Kementerian PANRB, nilai IKM dikonversi ke skala maksimum 100, dengan rumus sebagai berikut:

$$
IKM = \frac{IKM'}{\text{Skala maksimum penilaian}} \times 100 = \frac{IKM}{10} \times 100
$$

| Nilai Persepsi | Nilai Interval | Nilai Internal Konversi | Mutu Pelayanan | Kinerja Unit Pelayanan |
|:-------------:|:--------------|--------------:|:-------------:|:-------------:|
|       1        | 1,00 - 2, 5996 |           25,00 - 64,99 |       D        |       Tidak Baik       |
|       2        | 2,60 - 3,064   |           65,00 - 76,60 |       C        |      Kurang Baik       |
|       3        | 3,0644 - 3,532 |           76,61 - 88,30 |       B        |          Baik          |
|       4        | 3,5324 - 4, 00 |          88,31 - 100,00 |       A        |      Sangat Baik       |

: Nilai Kinerja Unit Pelayanan {#tbl-nilai-kinerja-2}

## Indeks Persepsi Kualitas Pelayanan (IPKP) Metode KemenPANRB

Indeks Persepsi Kualitas Pelayanan (IPKP) merupakan ukuran kualitas pelayanan yang diberikan oleh unit PST BPS sebagai unit penyelenggara pelayanan publik di BPS. Penghitungan IPKP berpedoman pada Surat Edaran Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 4 Tahun 2023 tentang Pengusulan dan Evaluasi Zona Integritas 2023 dan Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 14 Tahun 2017 tentang Pedoman Penyusunan Survei Kepuasan Masyarakat Unit Penyelenggara Pelayanan Publik.

Penghitungan IPKP sama dengan IKM yaitu diperoleh dengan menghitung rata-rata tertimbang skor tingkat kepuasan berdasarkan 9 atribut pertanyaan (variabel) sebagaimana diatur dalam peraturan tersebut yang terdapat dalam Blok II kuesioner VKD24. Nilai IPKP digunakan dalam pembangunan dan evaluasi Zona Integritas pada satuan kerja BPS dalam mendukung program Pembangunan dan Evaluasi Zona Integritas menuju Wilayah Bebas dari Korupsi dan Wilayah Birokrasi Bersih dan Melayani di Instansi Pemerintah sebagaimana diatur dalam Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 90 Tahun 2021.

Nilai IPKP dalam pelaksanaan evaluasi Zona Integritas menggunakan skala 4, sehingga nilai IPKP menggunakan nilai IKM yang dikonversi ke skala maksimum 4, dengan rumus sebagai berikut:

$$
IPKP = \frac{IKM}{100} \times \text{Skala maksimum penilaian} = \frac{IKM}{100} \times 4
$$

## Indeks Persepsi Anti Korupsi (IPAK) Metode BPS

Indeks Persepsi Anti Korupsi (IPAK) adalah indeks yang digunakan untuk memperoleh gambaran persepsi atau penilaian konsumen terhadap perilaku anti

korupsi pada pelayanan di PST BPS. Aspek penghitungan adalah terkait penerapan perilaku anti korupsi dalam memberikan pelayanan yang meliputi tidak ada diskriminasi, tidak ada praktik suap, tidak ada pungutan liar (pungli), serta tidak ada praktik percaloan. Nilai IPAK diperoleh dengan melakukan penghitungan rata-rata tertimbang skor tingkat kepuasan berdasarkan 5 atribut anti korupsi (variabel) yang ada di Blok II kuesioner VKD2024.

Langkah-langkah penghitungan IPAK sebagai berikut:

1.  Menghitung penimbang

Penimbang diperoleh dengan cara membagi rata-rata tingkat kepentingan masing-masing atribut anti korupsi dengan jumlah rata-rata tingkat kepentingan seluruh atribut anti korupsi. Rumus penimbang:

$$
w_i = \frac{\bar y_i}{\sum_{i = 1}^{5}{\bar y_i}}
$$

dengan:

$w_i$ adalah penimbang atribut pelayanan ke-$i$, $\sum_{i = 1}^{5}{w_i} = 1$;

$\bar y_i$ adalah rata-rata tingkat kepentingan atribut anti korupsi ke-$i$, $i$ = 1,2,3,4,5

2.  Menghitung rata-rata tertimbang skor kepuasan ($IPAK’$)

$IPAK’$ diperoleh dengan cara menghitung rata-rata tertimbang skor kepuasan berdasarkan 5 (lima) atribut anti korupsi. Rumus IPAK’ :

$$
IPAK' = \frac{\sum_{i = 1}^{5}{w_i \bar x_i}}{\sum_{i = 1}^{5}{w_i}} = \sum_{i = 1}^{5}{w_i\bar x_i}
$$

dengan $\bar x_i$ adalah rata-rata tingkat kepuasan atribut anti korupsi ke-$i$.

3.  Menghitung IPAK Penghitungan

IPAK’ menghasilkan nilai berkisar antara 1 sampai 10 sesuai dengan skala penilaian konsumen terhadap perilaku anti korupsi. IPAK merupakan hasil konversi nilai IPAK’ menggunakan rumus berikut:

$$
IPAK = \frac{IPAK'}{\text{skala maksimum penilaian}} \times 100 = \frac{IPAK'}{10} \times 100
$$

Nilai IPAK semakin mendekati 100 menunjukkan bahwa perilaku anti korupsi semakin diterapkan dengan sangat baik pada PST BPS.

## Indeks Persepsi Anti Korupsi (IPAK) Metode KemenPANRB

Indeks Persepsi Anti Korupsi (IPAK) adalah indeks yang digunakan untuk memperoleh gambaran persepsi atau penilaian konsumen terhadap perilaku anti korupsi pada unit PST BPS sebagai unit penyelenggara pelayanan publik di BPS. Penghitungan IPAK berpedoman pada Surat Edaran Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 4 Tahun 2023 tentang Pengusulan dan Evaluasi Zona Integritas 2023 dan Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 14 Tahun 2017 tentang Pedoman Penyusunan Survei Kepuasan Masyarakat Unit Penyelenggara Pelayanan Publik.

Nilai IPAK digunakan dalam pembangunan dan evaluasi Zona Integritas pada satuan kerja BPS dalam mendukung program Pembangunan dan Evaluasi Zona Integritas menuju Wilayah Bebas dari Korupsi dan Wilayah Birokrasi Bersih dan Melayani di Instansi Pemerintah sebagaimana diatur dalam Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 90 Tahun 2021.

Aspek penghitungan adalah terkait penerapan perilaku anti korupsi dalam memberikan pelayanan yang meliputi tidak ada diskriminasi, tidak ada praktik suap, tidak ada pungutan liar (pungli), serta tidak ada praktik percaloan. Nilai IPAK diperoleh dengan melakukan penghitungan rata-rata tertimbang skor tingkat

kepuasan berdasarkan 5 atribut anti korupsi (variabel) yang ada di Blok II kuesioner VKD2024.

Langkah-langkah penghitungan IPAK sebagai berikut:

1.  Menghitung Penimbang

Penimbang diperoleh dengan menggunakan "nilai rata-rata tertimbang" masing-masing atribut pelayanan. Dalam penghitungan penimbang, setiap atribut pelayanan memiliki penimbang yang sama. Nilai penimbang ditetapkan dengan rumus, sebagai berikut:

$$
\text{Bobot nilai rata-rata tertimbang} = \frac{\text{Jumlah Bobot}}{\text{Jumlah Atribut}} = \frac {1}{X} = N
$$

dengan $N$ adalah Bobot nilai per unsur. Sehingga nilai penimbang sebagai berikut

$$
\text{Bobot nilai rata-rata tertimbang} = \frac{\text{Jumlah Bobot}}{\text{Jumlah Atribut}} = \frac {1}{5} = 20
$$

2.  Menghitung IPAK

Penghitungan IPAK menggunakan pendekatan nilai rata-rata tertimbang dengan rumus sebagai berikut:

$$
IPAK' = \frac{\text{Total Nilai Persepsi per Atribut Perilaku}}{\text{Total Atribut Perilaku yang Terisi}} \times \text{Nilai Penimbang}
$$

Penghitungan IPAK’ menghasilkan nilai berkisar antara 1 sampai 10 sesuai dengan skala penilaian konsumen terhadap perilaku anti korupsi dalam kuesioner VKD2024. Nilai IPAK dalam pelaksanaan evaluasi Zona Integritas menggunakan skala 4, sehingga nilai IPAK’ dikonversi ke skala maksimum 4, dengan rumus sebagai berikut:

$$
IPAK = \frac{IPAK'}{100} \times \text{Skala maksimum penilaian} = \frac{IPAK'}{100} \times 4
$$
