# Kata Pegantar {.unnumbered}

Undang-Undang RI Nomor 25 Tahun 2009 tentang Pelayanan Publik mengatur bahwa setiap penyelenggara pelayanan publik berkewajiban melaksanakan evaluasi terhadap kinerja pelaksana pelayanan publik. Salah satu bentuk evaluasi ini diwujudkan melalui penyelenggaraan Survei Kepuasan Masyarakat (SKM) sebagaimana yang diatur dalam Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi RI Nomor 14 Tahun 2017 tentang Pedoman Penyusunan Survei Kepuasan Masyarakat Unit Penyelenggara Pelayanan Publik.

Badan Pusat Statistik (BPS), sebagai salah satu penyelenggara pelayanan publik yang menyediakan data dan informasi statistik, senantiasa berusaha memberikan pelayanan prima kepada konsumen. BPS telah menyelenggarakan SKM secara rutin setiap tahun yang diintegrasikan ke dalam Survei Kebutuhan Data (SKD). Survei ini selain bertujuan untuk mendapatkan tingkat kepuasan konsumen terhadap pelayanan data BPS, juga bertujuan untuk mengidentifikasi kebutuhan data dan tingkat kepuasan konsumen terhadap kualitas data yang dihasilkan BPS. Ketersediaan data dan informasi statistik yang dibutuhkan oleh pengguna data perlu dikaji guna menghasilkan data dan informasi statistik yang berkualitas serta mencapai visi BPS sebagai pelopor data statistik terpercaya untuk semua.

Laporan hasil pelaksanaan SKD2024 memberikan gambaran mengenai tingkat kepuasan pengguna layanan terhadap layanan pada Unit Pelayanan Statistik Terpadu (PST) BPS. Indikator yang disajikan dalam laporan Triwulan II Tahun 2024 mencakup Indeks Kepuasan Konsumen (IKK), Indeks Kepuasan Masyarakat (IKM), Indeks Persepsi Kualitas Pelayanan (IPKP) dan Indeks Persepsi Anti Korupsi (IPAK). Laporan ini terwujud berkat kerja sama yang baik antar unit kerja terkait. Kami berharap laporan ini dapat bermanfaat untuk memperbaiki kualitas dan kinerja pelayanan BPS. Saran dan masukan yang membangun sangat kami harapkan untuk perbaikan ke depan.

|     |                                  |
|:---:|---------------------------------:|
|     |            Maumere, 25 Juli 2024 |
|     |       Kepala BPS Kabupaten Sikka |
|     |                                  |
|     |                                  |
|     | Kristanto Setyo Utomo, SST, M.Si |


\listoftables
\listoffigures
